'use client'
import { Metadata } from "next";
import { useState } from "react"
export const metadata: Metadata = {
  title: "Tested App",
  description: "Generated by create next app",
};
interface IProps {
    count?: number
}
export default function Phone(props: IProps) {
    const [count, setCount] = useState(props.count || 0)
    const handleClick = () => {
        setCount(count + 1)
    }
    return (
        <main className="bg-amber-50">
            <section className="container">
                <h1 className="text-2xl font-semibold">Welcome!</h1>
                <p>{count}</p>
                <button onClick={handleClick}>Change</button>
            </section>
        </main>
    )
}